"""Unified evidence markdown generator.

Produces ONE markdown report for either path (ExternalCopilot via sf agent test,
or InternalCopilot via Agent API). Each case shows utterance / topic / agent
response / per-assertion results, using the filtered scores from scorer.py.

Privacy: this file NEVER contains secrets or tokens — only test utterances,
agent responses, and pass/fail. Callers must pass already-scored case dicts.
"""
import datetime


def _fmt_actions(actions):
    if not actions:
        return "—"
    return ", ".join("`%s`" % a for a in actions)


def render_evidence(*, agent_name, org_alias, agent_type, path_label,
                    results, judge_label=None):
    """Render the full evidence markdown string."""
    from .scorer import aggregate

    agg, total_pass, total = aggregate(results)
    pct = round(100 * total_pass / total) if total else 0
    now = datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")

    out = []
    out.append("# Agent Probe Evidence — %s" % agent_name)
    out.append("")
    out.append("> Generated by `agentforce-probe`. Fully local; no data leaves "
               "this machine except calls to Salesforce and (Internal path only) "
               "the configured judge LLM. No secrets/tokens are recorded here.")
    out.append("")
    out.append("- **Org:** %s" % org_alias)
    out.append("- **Agent:** %s" % agent_name)
    out.append("- **Type:** %s" % agent_type)
    out.append("- **Verification path:** %s" % path_label)
    if judge_label:
        out.append("- **LLM judge:** %s" % judge_label)
    out.append("- **Generated:** %s" % now)
    out.append("")
    out.append("**Overall: %d/%d = %d%%**  ·  topic %d/%d  ·  actions %d/%d  ·  "
               "output %d/%d" % (
                   total_pass, total, pct,
                   agg["topic"][0], agg["topic"][1],
                   agg["actions"][0], agg["actions"][1],
                   agg["output"][0], agg["output"][1]))
    out.append("")
    out.append("> `output` (LLM-as-judge) is the primary behavioral signal. "
               "`-` = assertion intentionally not set for this case (per the "
               "assertion-filtering rules).")
    out.append("")

    # Per-case detail blocks (no pipe tables — Telegram/markdown friendly).
    for r in results:
        out.append("## Case %s" % r["number"])
        out.append("")
        out.append("**Utterance:** %s" % r["utterance"])
        out.append("")
        out.append("- topic: **%s**%s" % (
            r["topic"],
            _topic_detail(r)))
        out.append("- actions: **%s**%s" % (
            r["actions"],
            _actions_detail(r)))
        out.append("- output (judge): **%s**" % r["output"])
        if r.get("judge_reason"):
            out.append("  - reason: %s" % r["judge_reason"])
        out.append("")
        out.append("**Agent response:**")
        out.append("")
        resp = (r.get("response") or "").strip() or "_(no response captured)_"
        for line in resp.splitlines() or [resp]:
            out.append("> %s" % line)
        out.append("")

    return "\n".join(out) + "\n"


def _topic_detail(r):
    if r["topic"] == "-":
        return "  _(no expectedTopic)_"
    exp = r.get("expectedTopic")
    act = r.get("actualTopic")
    if exp is None and act is None:
        return ""
    return "  (expected `%s`, got `%s`)" % (exp, act if act is not None else "?")


def _actions_detail(r):
    if r["actions"] == "-":
        return "  _(no expectedActions)_"
    exp = _fmt_actions(r.get("expectedActions"))
    act = _fmt_actions(r.get("actualActions"))
    return "  (expected %s, got %s)" % (exp, act)


def write_evidence(path, content):
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
