"""Unified evidence markdown generator.

Produces ONE markdown report for either path (ExternalCopilot via sf agent test,
or InternalCopilot via Agent API). Each case shows utterance / topic / agent
response / per-assertion results, using the filtered scores from scorer.py.

Privacy: this file NEVER contains secrets or tokens — only test utterances,
agent responses, and pass/fail. Callers must pass already-scored case dicts.
"""

import datetime


def _fmt_actions(actions):
    if not actions:
        return "—"
    return ", ".join(f"`{a}`" for a in actions)


def render_evidence(*, agent_name, org_alias, agent_type, path_label, results, judge_label=None, ungrounded=False):
    """Render the full evidence markdown string."""
    from .scorer import aggregate

    agg, total_pass, total = aggregate(results)
    pct = round(100 * total_pass / total) if total else 0
    now = datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")

    out = []
    out.append(f"# Agent Probe Evidence — {agent_name}")
    out.append("")
    if ungrounded:
        out.append(
            "> ⚠️ **MOCK JUDGE — NOT A REAL PASS RATE.** This run used an ungrounded judge that only checks whether the agent replied. The scores below are NOT a measure of correctness."
        )
        out.append("")
    out.append(
        "> Generated by `agentforce-probe`. Fully local; no data leaves "
        "this machine except calls to Salesforce and (Internal path only) "
        "the configured judge LLM. No secrets/tokens are recorded here."
    )
    out.append("")
    out.append(f"- **Org:** {org_alias}")
    out.append(f"- **Agent:** {agent_name}")
    out.append(f"- **Type:** {agent_type}")
    out.append(f"- **Verification path:** {path_label}")
    if judge_label:
        if ungrounded:
            out.append(f"- **LLM judge:** {judge_label} (UNGROUNDED — not a real pass rate)")
        else:
            out.append(f"- **LLM judge:** {judge_label}")
    out.append(f"- **Generated:** {now}")
    out.append("")
    out.append(
        f"**Overall: {total_pass}/{total} = {pct}%**  ·  topic {agg['topic'][0]}/{agg['topic'][1]}  ·  actions {agg['actions'][0]}/{agg['actions'][1]}  ·  output {agg['output'][0]}/{agg['output'][1]}"
    )
    out.append("")
    out.append(
        "> `output` (LLM-as-judge) is the primary behavioral signal. "
        "`-` = assertion intentionally not set for this case (per the "
        "assertion-filtering rules)."
    )
    out.append("")

    # Per-case detail blocks (no pipe tables — Telegram/markdown friendly).
    for r in results:
        out.append("## Case {}".format(r["number"]))
        out.append("")
        out.append("**Utterance:** {}".format(r["utterance"]))
        out.append("")
        out.append("- topic: **{}**{}".format(r["topic"], _topic_detail(r)))
        out.append("- actions: **{}**{}".format(r["actions"], _actions_detail(r)))
        out.append("- output (judge): **{}**".format(r["output"]))
        if r.get("judge_reason"):
            out.append("  - reason: {}".format(r["judge_reason"]))
        axes = r.get("axes")
        if axes:
            from . import judge as _judge
            comp = _judge.composite_score(axes)
            parts = [f"{k} {axes[k]:.2g}" for k in _judge.JUDGE_AXES if k in axes]
            out.append("  - axes: {}  ·  composite {:.2f}".format(" · ".join(parts), comp))
        out.append("")
        out.append("**Agent response:**")
        out.append("")
        resp = (r.get("response") or "").strip() or "_(no response captured)_"
        for line in resp.splitlines() or [resp]:
            out.append(f"> {line}")
        out.append("")

    return "\n".join(out) + "\n"


def _topic_detail(r):
    if r["topic"] == "-":
        return "  _(no expectedTopic)_"
    exp = r.get("expectedTopic")
    act = r.get("actualTopic")
    if exp is None and act is None:
        return ""
    return "  (expected `{}`, got `{}`)".format(exp, act if act is not None else "?")


def _actions_detail(r):
    if r["actions"] == "-":
        return "  _(no expectedActions)_"
    exp = _fmt_actions(r.get("expectedActions"))
    act = _fmt_actions(r.get("actualActions"))
    return f"  (expected {exp}, got {act})"


def write_evidence(path, content):
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
